---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.5
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  #system: bindep.txt

images:
  base_image:
    name: quay.io/centos/centos:stream8

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
  prepend_base: |
    RUN yum update -y && \
    yum install glibc-all-langpacks langpacks-en -y && \
    yum upgrade -y && \
    yum install python39 -y && \
    yum clean all && \
    rm -rf /var/cache/yum
